### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by johnreb20** [yoraish/botello#3]
Hi Im getting this error when I roslaunch it
"/home/john/botello/botello_ws/src/tello_driver/nodes/tello_driver_node", line 103, in __init__     super(TelloNode, self).__init__(port=9000) TypeError: __init__() got an unexpected keyword argument 'port'
Thanks.

**Comment by yoraish** [comment]
Hi!

I have a feeling that there is a version mismatch between some packages that you are using (to the ones I was using). I am planning on moving much of the code to newer versions of Ubuntu/ROS at some point in the next few months. If you do some work on that, please open a PR and contribute :smiley:

**Comment by johnreb20** [comment]
Hi yoraish,

I solved the issue with first installing the tello_driver and then merging with the clone.

But I not getting any messages on raw_image 

[ERROR] [1683157786.327657]: fgrab: pyav decoder failed - 'TelloNode' object has no attribute 'caminfo'

Thanks.

**Comment by johnreb20** [comment]
Hi!

It got solved and worked on noetic.

Thanks

**Comment by yoraish** [comment]
Oh nice! If you can, please commit your code as a pull-request. Several people would benefit from it.

**Comment by yoraish** [comment]
Closing.
